### ISSUE TITLE
Design for the dashboard page required

### ISSUE THREAD

**Issue by chirayu-joshi** [clubgamma/2x-productivity#1]
The current flow of the project is described in [wiki section](https://github.com/clubgamma/2x-productivity/wiki) of this project. **You are free** to present your point of views on it. You can tell me to add/remove any point over there.

Right now, we will start from a basic dashboard page. We will just create a static dashboard page for now, then we will start creating **create task** page. So, to maintain uniformity, it is nice to create a design first. 

If anyone has the skills of **graphics design**, then he/she can discuss the design in this issue. If anyone finds a good design, then we can also take inspiration from it, and create our own unique design. Please let us all first confirm the design in this issue and then send pull request containing design.

**Comment by precious-omovoiye** [comment]
I want to make contributions as a designer

**Comment by chirayu-joshi** [comment]
Thanks @precious-omovoiye for showing interest. We will be very happy to receive any type of participation from you. 

You can start working on creating design for this project. 

If you have any doubt or query, you can tell us in this issue, or open new issue, or you can also tell us on [discord](https://discord.gg/kjnp6wU)

**Comment by precious-omovoiye** [comment]
Thanks @chirayu-joshi I will get to work immediately

**Comment by precious-omovoiye** [comment]
@chirayu-joshi design is ongoing already, however, I might be needing more information for the design, I will reach out when necessary.

**Comment by juniorHotes** [comment]
I also want to participate in this project, as it does not yet have an interface, I will create one and send it to you to decide if you agree.

**Comment by chirayu-joshi** [comment]
Hey @juniorHotes ,
Thanks for showing interest in this project. We will be happy to see any kind of participation from you. 

You may create an interface for the project. And if you haven't gone through wiki and readme, please consider to go through it to have an idea about the project.

**Comment by juniorHotes** [comment]
Hi! It would be more or less this idea that I had of the interface, it is not yet complete, you can already take a look by accessing the figma link.
https://www.figma.com/file/AgF7Gbm5t1qJGLoQnNIUee/2x-Productivity?node-id=5%3A4

**Comment by juniorHotes** [comment]
Yes, I will provide

**Comment by chirayu-joshi** [comment]
Thanks @juniorHotes for your contribution. Due to my exams, I couldn't merge it 2 days before. I am closing this issue, you can reopen this issue or create new one if you wish.
